{% set version = "9999" %}

package:
  name: orthofinder-dl
  version: {{ version }}

build:
  number: 0
  skip: False # [not py27]

source:
  git_url: https://github.com/thiesgehrmann/OrthoFinder.git

requirements:
  run:
    - python
    - scipy
    - blast
    - diamond
    - mcl
    - louvain_generic
    - fastme
    - dlcpar

test:
  commands:
    - orthofinder-dl.py > /dev/null

about:
  home: https://github.com/thiesgehrmann/OrthoFinder
  summary: Accurate inference of orthogroups, orthologues, gene trees and rooted species tree made easy! With Diamond instead of Blast, and Louvain instead of MCL
  license: GPLv3
